### ISSUE TITLE
VODs missing

### ISSUE THREAD

**Issue by tom-huntington** [ThePrimeagen/tyrone-biggums#6]
I was hoping to learn server programming by watching the VODs from the start, building and running the commits:
https://github.com/ThePrimeagen/tyrone-biggums/blob/1ddb63fac0a26c6c37ec39ceb7b6175b127fdcbc/README.md?plain=1#L37

But it seems like you where streaming on youtube when you started the project, then set the past live streams to private.

Could you set the past live streams to unlisted and provide the links please?

**Comment by csj0oe** [comment]
Hi @tom-huntington, I'm a little bit late to the party, but did you manage to find the VODs ?

**Comment by tom-huntington** [comment]
Nope
